### PR TITLE
Update to 0.9.9 Master Branch

### PR DESCRIPTION
**Pull request by explit28**
Hello @spark2k06. Could you please update your spark2k06/8088_bios alterantative branch to the latest skiselev/8088_bios master branch?

Thanks

### CODE REVIEW

**Comment by spark2k06** [comment]
I haven't touched this project for a while and I don't have much time to check it, if you have tested it well and you think everything is ok I accept the pull request.

**Comment by explit28** [comment]
> I haven't touched this project for a while and I don't have much time to check it, if you have tested it well and you think everything is ok I accept the pull request.

Yes, @spark2k06 I tested it, it works very good. The bugs with b/w VGA Monitor are solved yet.

**Comment by spark2k06** [comment]
Ok, however it is not possible to merge directly, there are conflicts with the project I keep in my repository. I'll take a look at it when I can.

**Comment by spark2k06** [comment]
I will not have time to review conflicts. I reject the pull request, I suggest you download the main branch from my repository, and apply the changes to it so I don't have to check all the conflicts that occur in the sources... once done, make a pull request again. 

Sorry for the inconvenience, I can't maintain this fork. Alternatively, you can fork this project and manage the updates yourself.

image

**Comment by explit28** [comment]
Thanks for the info @spark2k06 Its indeed not easy. I updated the last @skiselev  0.9.9 branch with your changes from the alternative branch - but ended with an bricked bios :)
For now i a reprogrammed back the latest @skiselev 0.9.9 master branch. But it would be cool to have your OPL and Debug changes in the master branch....

Lets see...

**Comment by explit28** [comment]
Hi @spark2k06. So now i had more luck. I updated your last alternative Branch 0.9.8a to the latest @skiselev Version 0.9.9
I tested it on my Micro8088 and it works without any Problems.
So if you could merge my pull request - it would be great!

Thanks

Pawel

**Comment by spark2k06** [comment]
Done!

Thanks for your contribution 😉

**Comment by skiselev** [comment]
@explit7 you probably will want to repeat the process again 😉
I made a few more fixes to 8088 BIOS, some are more important than others (e.g. floppy subsystem fixes)

**Comment by explit28** [comment]
> @explit7 you probably will want to repeat the process again wink I made a few more fixes to 8088 BIOS, some are more important than others (e.g. floppy subsystem fixes)

Made it, @skiselev ;) - Thanks for your work!
Sorry, @spark2k06 - You need to push the button again :)

**Comment by spark2k06** [comment]
Done!

**Pull request closed without merging**
